// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GoodCents",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "GoodCents",
            targets: ["AppModule"],
            bundleIdentifier: "app.GoodCents.Legacy",
            teamIdentifier: "4TD3JXVDW7",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .finance
        )
    ],
    dependencies: [
        .package(url: "https://github.com/ottijp/confetti-swiftui", "0.1.0"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Confetti", package: "confetti-swiftui")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)